//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ehrungsprogramm.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ehrungsprogramm.Properties.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Board Member ähnelt.
        /// </summary>
        public static string FunctionType_BOARD_MEMBER {
            get {
                return ResourceManager.GetString("FunctionType_BOARD_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Head of Departement ähnelt.
        /// </summary>
        public static string FunctionType_HEAD_OF_DEPARTEMENT {
            get {
                return ResourceManager.GetString("FunctionType_HEAD_OF_DEPARTEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other Function ähnelt.
        /// </summary>
        public static string FunctionType_OTHER_FUNCTION {
            get {
                return ResourceManager.GetString("FunctionType_OTHER_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        public static string FunctionType_UNKNOWN {
            get {
                return ResourceManager.GetString("FunctionType_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BLSV 20 ähnelt.
        /// </summary>
        public static string RewardTypes_BLSV20 {
            get {
                return ResourceManager.GetString("RewardTypes_BLSV20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BLSV 25 ähnelt.
        /// </summary>
        public static string RewardTypes_BLSV25 {
            get {
                return ResourceManager.GetString("RewardTypes_BLSV25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BLSV 30 ähnelt.
        /// </summary>
        public static string RewardTypes_BLSV30 {
            get {
                return ResourceManager.GetString("RewardTypes_BLSV30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BLSV 40 ähnelt.
        /// </summary>
        public static string RewardTypes_BLSV40 {
            get {
                return ResourceManager.GetString("RewardTypes_BLSV40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BLSV 45 ähnelt.
        /// </summary>
        public static string RewardTypes_BLSV45 {
            get {
                return ResourceManager.GetString("RewardTypes_BLSV45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BLSV 50 ähnelt.
        /// </summary>
        public static string RewardTypes_BLSV50 {
            get {
                return ResourceManager.GetString("RewardTypes_BLSV50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BLSV 60 ähnelt.
        /// </summary>
        public static string RewardTypes_BLSV60 {
            get {
                return ResourceManager.GetString("RewardTypes_BLSV60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BLSV 70 ähnelt.
        /// </summary>
        public static string RewardTypes_BLSV70 {
            get {
                return ResourceManager.GetString("RewardTypes_BLSV70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BLSV 80 ähnelt.
        /// </summary>
        public static string RewardTypes_BLSV80 {
            get {
                return ResourceManager.GetString("RewardTypes_BLSV80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other Reward ähnelt.
        /// </summary>
        public static string RewardTypes_OTHER {
            get {
                return ResourceManager.GetString("RewardTypes_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TSV Gold ähnelt.
        /// </summary>
        public static string RewardTypes_TSVGOLD {
            get {
                return ResourceManager.GetString("RewardTypes_TSVGOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TSV Honorary ähnelt.
        /// </summary>
        public static string RewardTypes_TSVHONORARY {
            get {
                return ResourceManager.GetString("RewardTypes_TSVHONORARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TSV Silver ähnelt.
        /// </summary>
        public static string RewardTypes_TSVSILVER {
            get {
                return ResourceManager.GetString("RewardTypes_TSVSILVER", resourceCulture);
            }
        }
    }
}
