//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ehrungsprogramm.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ehrungsprogramm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reward Program ähnelt.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available BLSV Rewards ähnelt.
        /// </summary>
        public static string AvailableBLSVRewardsCountString {
            get {
                return ResourceManager.GetString("AvailableBLSVRewardsCountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available ähnelt.
        /// </summary>
        public static string AvailableString {
            get {
                return ResourceManager.GetString("AvailableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available TSV Rewards ähnelt.
        /// </summary>
        public static string AvailableTSVRewardsCountString {
            get {
                return ResourceManager.GetString("AvailableTSVRewardsCountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Birth Date ähnelt.
        /// </summary>
        public static string BirthDateString {
            get {
                return ResourceManager.GetString("BirthDateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caution: The calculation deadline is not set.
        ///This leads to zero scores for all people! ähnelt.
        /// </summary>
        public static string CalculationDeadlineNotSetString {
            get {
                return ResourceManager.GetString("CalculationDeadlineNotSetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculation Deadline ähnelt.
        /// </summary>
        public static string CalculationDeadlineString {
            get {
                return ResourceManager.GetString("CalculationDeadlineString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really clear the database? All imported people will be deleted! ähnelt.
        /// </summary>
        public static string ClearDatabaseConfirmationString {
            get {
                return ResourceManager.GetString("ClearDatabaseConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Database ähnelt.
        /// </summary>
        public static string ClearDatabaseString {
            get {
                return ResourceManager.GetString("ClearDatabaseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database Statistics ähnelt.
        /// </summary>
        public static string DatabaseStatisticsString {
            get {
                return ResourceManager.GetString("DatabaseStatisticsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PersonDetail_{0}.pdf ähnelt.
        /// </summary>
        public static string DefaultFileNamePersonDetail {
            get {
                return ResourceManager.GetString("DefaultFileNamePersonDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PersonOverview.pdf ähnelt.
        /// </summary>
        public static string DefaultFileNamePersonOverview {
            get {
                return ResourceManager.GetString("DefaultFileNamePersonOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RewardOverview.pdf ähnelt.
        /// </summary>
        public static string DefaultFileNameRewardOverview {
            get {
                return ResourceManager.GetString("DefaultFileNameRewardOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Departements ähnelt.
        /// </summary>
        public static string DepartementsString {
            get {
                return ResourceManager.GetString("DepartementsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string DescriptionString {
            get {
                return ResourceManager.GetString("DescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eff. Board Member Years ähnelt.
        /// </summary>
        public static string EffectiveBoardMemberYears {
            get {
                return ResourceManager.GetString("EffectiveBoardMemberYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eff. Head of Departement Years ähnelt.
        /// </summary>
        public static string EffectiveHeadOfDepartementYears {
            get {
                return ResourceManager.GetString("EffectiveHeadOfDepartementYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eff. Other Years ähnelt.
        /// </summary>
        public static string EffectiveOtherFunctionsYears {
            get {
                return ResourceManager.GetString("EffectiveOtherFunctionsYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        public static string EnglishString {
            get {
                return ResourceManager.GetString("EnglishString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entry Date ähnelt.
        /// </summary>
        public static string EntryDateString {
            get {
                return ResourceManager.GetString("EntryDateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSV Files|*.csv|Textfiles|*.txt|All Files|*.* ähnelt.
        /// </summary>
        public static string FileFilterInputFile {
            get {
                return ResourceManager.GetString("FileFilterInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF Files|*.pdf|All Files|*.* ähnelt.
        /// </summary>
        public static string FileFilterPDF {
            get {
                return ResourceManager.GetString("FileFilterPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} item(s) visible ({1} available) ähnelt.
        /// </summary>
        public static string FilteredListViewNumElementsFilteredFormatString {
            get {
                return ResourceManager.GetString("FilteredListViewNumElementsFilteredFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} item(s) ähnelt.
        /// </summary>
        public static string FilteredListViewNumElementsNonFilteredFormatString {
            get {
                return ResourceManager.GetString("FilteredListViewNumElementsNonFilteredFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Name ähnelt.
        /// </summary>
        public static string FirstNameString {
            get {
                return ResourceManager.GetString("FirstNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Functions ähnelt.
        /// </summary>
        public static string FunctionsString {
            get {
                return ResourceManager.GetString("FunctionsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Function Type ähnelt.
        /// </summary>
        public static string FunctionTypeString {
            get {
                return ResourceManager.GetString("FunctionTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Years in Function ähnelt.
        /// </summary>
        public static string FunctionYearsString {
            get {
                return ResourceManager.GetString("FunctionYearsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate Test Data ähnelt.
        /// </summary>
        public static string GenerateTestDataString {
            get {
                return ResourceManager.GetString("GenerateTestDataString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        /// </summary>
        public static string GermanString {
            get {
                return ResourceManager.GetString("GermanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import from File ähnelt.
        /// </summary>
        public static string ImportDataFromFileString {
            get {
                return ResourceManager.GetString("ImportDataFromFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Imported File ähnelt.
        /// </summary>
        public static string LastImportedFileString {
            get {
                return ResourceManager.GetString("LastImportedFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move to the Manage Database page to import data. ähnelt.
        /// </summary>
        public static string ListEmptyNavigateToManageDatabaseString {
            get {
                return ResourceManager.GetString("ListEmptyNavigateToManageDatabaseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The list is empty. ähnelt.
        /// </summary>
        public static string ListEmptyString {
            get {
                return ResourceManager.GetString("ListEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main ähnelt.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage Database ähnelt.
        /// </summary>
        public static string ManageDatabasePageTitle {
            get {
                return ResourceManager.GetString("ManageDatabasePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Membership Years ähnelt.
        /// </summary>
        public static string MembershipYearsString {
            get {
                return ResourceManager.GetString("MembershipYearsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string NameString {
            get {
                return ResourceManager.GetString("NameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No BLSV rewards available ähnelt.
        /// </summary>
        public static string NoBLSVRewardsString {
            get {
                return ResourceManager.GetString("NoBLSVRewardsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No TSV rewards available ähnelt.
        /// </summary>
        public static string NoTSVRewardsString {
            get {
                return ResourceManager.GetString("NoTSVRewardsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Obtained Date ähnelt.
        /// </summary>
        public static string ObtainedDateString {
            get {
                return ResourceManager.GetString("ObtainedDateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parsing Errors Count ähnelt.
        /// </summary>
        public static string ParsingErrorsCountString {
            get {
                return ResourceManager.GetString("ParsingErrorsCountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Person Detail ähnelt.
        /// </summary>
        public static string PersonDetailPageTitle {
            get {
                return ResourceManager.GetString("PersonDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Person ID ähnelt.
        /// </summary>
        public static string PersonIdString {
            get {
                return ResourceManager.GetString("PersonIdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Persons Count ähnelt.
        /// </summary>
        public static string PersonsCountString {
            get {
                return ResourceManager.GetString("PersonsCountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Persons ähnelt.
        /// </summary>
        public static string PersonsPageTitle {
            get {
                return ResourceManager.GetString("PersonsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Points ähnelt.
        /// </summary>
        public static string PointsString {
            get {
                return ResourceManager.GetString("PointsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Point ähnelt.
        /// </summary>
        public static string PointString {
            get {
                return ResourceManager.GetString("PointString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print ähnelt.
        /// </summary>
        public static string PrintString {
            get {
                return ResourceManager.GetString("PrintString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reload Last File ähnelt.
        /// </summary>
        public static string ReloadDataFileString {
            get {
                return ResourceManager.GetString("ReloadDataFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die G ähnelt.
        /// </summary>
        public static string RewardIconGoldString {
            get {
                return ResourceManager.GetString("RewardIconGoldString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die H ähnelt.
        /// </summary>
        public static string RewardIconHonoraryString {
            get {
                return ResourceManager.GetString("RewardIconHonoraryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S ähnelt.
        /// </summary>
        public static string RewardIconSilverString {
            get {
                return ResourceManager.GetString("RewardIconSilverString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rewards ähnelt.
        /// </summary>
        public static string RewardsPageTitle {
            get {
                return ResourceManager.GetString("RewardsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rewards ähnelt.
        /// </summary>
        public static string RewardsString {
            get {
                return ResourceManager.GetString("RewardsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rewards are only shown if the highest available reward isn&apos;t obtained yet.
        ///If the currently highest reward is already obtained, it isn&apos;t shown. ähnelt.
        /// </summary>
        public static string RewardVisibilityInfoString {
            get {
                return ResourceManager.GetString("RewardVisibilityInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score BLSV ähnelt.
        /// </summary>
        public static string ScoreBLSVString {
            get {
                return ResourceManager.GetString("ScoreBLSVString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score TSV ähnelt.
        /// </summary>
        public static string ScoreTSVString {
            get {
                return ResourceManager.GetString("ScoreTSVString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program to manage the rewards of the TSV Illertissen. ähnelt.
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About this application ähnelt.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Theme ähnelt.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Personalization ähnelt.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark ähnelt.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light ähnelt.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go back ähnelt.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open or close navigation ähnelt.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main ähnelt.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage Database ähnelt.
        /// </summary>
        public static string ShellManageDatabasePage {
            get {
                return ResourceManager.GetString("ShellManageDatabasePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Persons ähnelt.
        /// </summary>
        public static string ShellPersonsPage {
            get {
                return ResourceManager.GetString("ShellPersonsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rewards ähnelt.
        /// </summary>
        public static string ShellRewardsPage {
            get {
                return ResourceManager.GetString("ShellRewardsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successful ähnelt.
        /// </summary>
        public static string SuccessfulString {
            get {
                return ResourceManager.GetString("SuccessfulString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Period ähnelt.
        /// </summary>
        public static string TimePeriodString {
            get {
                return ResourceManager.GetString("TimePeriodString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Today ähnelt.
        /// </summary>
        public static string TodayString {
            get {
                return ResourceManager.GetString("TodayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TSVLogo {
            get {
                object obj = ResourceManager.GetObject("TSVLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown Functions Count ähnelt.
        /// </summary>
        public static string UnknownFunctionsCountString {
            get {
                return ResourceManager.GetString("UnknownFunctionsCountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visible Items ähnelt.
        /// </summary>
        public static string VisibleItemsString {
            get {
                return ResourceManager.GetString("VisibleItemsString", resourceCulture);
            }
        }
    }
}
